import { StyleSheet } from 'react-native';
import { fn } from './normalize';

export const typography = StyleSheet.create({
  textAuto: { textAlign: 'auto' },
  textLeft: { textAlign: 'left' },
  textRight: { textAlign: 'right' },
  textCenter: { textAlign: 'center' },
  textJustify: { textAlign: 'justify' },
  normalCase: { textTransform: 'none' },
  uppercase: { textTransform: 'uppercase' },
  lowercase: { textTransform: 'lowercase' },
  capitalize: { textTransform: 'capitalize' },
  textXs: { fontSize: fn(12) },
  textSm: { fontSize: fn(14) },
  textBase: { fontSize: fn(16) },
  textLg: { fontSize: fn(18) },
  textXl: { fontSize: fn(20) },
  text2xl: { fontSize: fn(24) },
  text3xl: { fontSize: fn(30) },
  text4xl: { fontSize: fn(36) },
  text5xl: { fontSize: fn(48) },
  text6xl: { fontSize: fn(64) },
  notItalic: { fontStyle: 'normal' },
  italic: { fontStyle: 'italic' },
  fontW100: { fontWeight: '100' },
  fontW200: { fontWeight: '200' },
  fontW300: { fontWeight: '300' },
  fontW400: { fontWeight: '400' },
  fontW500: { fontWeight: '500' },
  fontW600: { fontWeight: '600' },
  fontW700: { fontWeight: '700' },
  fontW800: { fontWeight: '800' },
  fontW900: { fontWeight: '900' },

  displayLarge: { fontSize: fn(56), fontWeight: '400' },
  displayMedium: { fontSize: fn(44), fontWeight: '400' },
  displaySmall: { fontSize: fn(36), fontWeight: '400' },
  headingLarge: { fontSize: fn(32), fontWeight: '400' },
  headingMedium: { fontSize: fn(28), fontWeight: '400' },
  headingSmall: { fontSize: fn(24), fontWeight: '400' },

  titleLarge: { fontSize: fn(22), fontWeight: '400' },
  titleMedium: { fontSize: fn(16), fontWeight: '500' },
  titleSmall: { fontSize: fn(14), fontWeight: '500' },

  bodyLarge: { fontSize: fn(16), fontWeight: '400' },
  bodyMedium: { fontSize: fn(14), fontWeight: '400' },
  bodySmall: { fontSize: fn(12), fontWeight: '400' },
  labelLarge: { fontSize: fn(14), fontWeight: '500' },
  labelMedium: { fontSize: fn(12), fontWeight: '500' },
  labelSmall: { fontSize: fn(11), fontWeight: '500' },
  textShadow: {
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { height: 1, width: 1 },
    textShadowRadius: 6,
  },
});
